<a href="https://colab.research.google.com/github/chetools/CHE4071_Spring2025/blob/main/MultilinearRegressionRungePhenomena.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
import pandas as pd
from plotly.subplots import make_subplots

In [4]:
df = pd.read_excel('McCollumData.xlsx')

In [7]:
xdata = df['xdata'].values
ydata = df['ydata'].values

In [8]:
Q = np.c_[xdata**2, np.sin(1.5*xdata), np.ones_like(xdata)]

In [13]:
np.linalg.lstsq(Q,ydata)

(array([0.49957544, 1.10203601, 2.09934583]),
 array([0.00889625]),
 np.int32(3),
 array([20.15930728,  7.24431163,  2.34380421]))

In [93]:
N=25
xdata = np.linspace(-1,1,N)

xdata = np.polynomial.chebyshev.chebpts1(N)
ydata = 1/(1+25*xdata**2)

In [94]:
xplot = np.linspace(-1,1,100)
Qplot=np.vander(xplot, N)

In [95]:
coeff = np.polyfit(xdata,ydata,deg=N-1)

In [96]:
fig=make_subplots()
fig.add_scatter(x=xdata, y=ydata, mode='markers')
fig.add_scatter(x=xplot, y=Qplot@coeff, mode='lines')
fig.update_layout(width=700, height=400, template='plotly_dark')

array([-0.98768834, -0.89100652, -0.70710678, -0.4539905 , -0.15643447,
        0.15643447,  0.4539905 ,  0.70710678,  0.89100652,  0.98768834])